version: '3'

services:
  lib:
    build: .
    depends_on:
      - redis
      - ftp
    environment:
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - SHELL=/bin/bash
    volumes:
      - ./:/code
      - ~/.netrc:/home/nens/.netrc  # github authentication
      - ~/.cache:/home/nens/.cache  # shared cache
    command: tail -F anything
  redis:
    image: redis:3-alpine
  ftp:
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: nrr
      FTP_USER_PASS: nrr
      FTP_USER_HOME: /home/nrr
